apiVersion: v1
data:
  jgroups.jceks: zs7OzgAAAAIAAAABAAAAAwAHamdyb3VwcwAAAWdkJG9UrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAARMA8ECPaZwnnKRM8uAgMDDUB1cQB+AAUAAAEI1CiNLfEl/4QNj5YItFPxa5IGRJto6diGPPcLdTEXDvPn4WGLA84rLTaLFWVyVaXl9bITo5SckNXhCgS/nam9uUWjv85Bh5KzEIalNWjuwOauiVr1twq9Hdxx2rEHeOx6x+haBTL8dcOdF2O+iRSPk5zv4O8leZeiH77z0xOvw9zrsTH2jVPFXNC40mXzepduZtF85FX3mOJVstW4eif/zNBwxL9BQMYu7rqsFmCLHeAs8SnCcX5X4utV4TiKqtYfYgfR4Y+1+zWXHteP/UYCUOQQRHUs8rZjcr1pXrpjl3kp3ieS1S8/cyhkYGEI8Ukm8mminnj5hi5k4wuRk7Y5BkKXOYAcBm14dAAWUEJFV2l0aE1ENUFuZFRyaXBsZURFU3QAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVOm0gxZZB205bTzOJA/M9QKEjhjIA==
kind: Secret
metadata:
  creationTimestamp: 2018-12-05T09:18:42Z
  name: sso-jgroup-secret
  namespace: sso-marcigliana
  resourceVersion: "20135051"
  selfLink: /api/v1/namespaces/sso-marcigliana/secrets/sso-jgroup-secret
  uid: c26b87ad-f86e-11e8-b974-005056ba2383
type: Opaque
